services:
  aaadb:
    image: bitnami/postgresql:16
    container_name: aaadb
    restart: no
    tty: true
    ports:
      - "5432:5432"
    volumes:
      - aaadb:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=pass123
      
  jupyter:
    image: quay.io/jupyter/scipy-notebook:python-3.12
    container_name: jupyter
    ports:
    - "8888:8888"
      
volumes:
  aaadb:
