"""empty message

Revision ID: 8465603b5bca
Revises: 
Create Date: 2025-03-12 15:03:28.334842

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '8465603b5bca'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pokemon',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=199), nullable=False),
    sa.Column('type', sqlmodel.sql.sqltypes.AutoString(length=40), nullable=False),
    sa.Column('health', sa.Integer(), nullable=False),
    sa.Column('weakness', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('evolution', sa.Integer(), nullable=False),
    sa.Column('notes', sqlmodel.sql.sqltypes.AutoString(length=256), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('trainerxyz123',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=199), nullable=False),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(length=256), nullable=False),
    sa.Column('region', sqlmodel.sql.sqltypes.AutoString(length=199), nullable=False),
    sa.Column('type', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('gender', sqlmodel.sql.sqltypes.AutoString(length=1), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('trainerxyz123')
    op.drop_table('pokemon')
    # ### end Alembic commands ###
