"""empty message

Revision ID: a815dacb1cc4
Revises: 52305f4244c7
Create Date: 2025-03-19 15:02:32.903915

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'a815dacb1cc4'
down_revision: Union[str, None] = '52305f4244c7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('weapon_character_id_fkey', 'weapon', type_='foreignkey')
    op.create_foreign_key(None, 'weapon', 'character', ['character_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'weapon', type_='foreignkey')
    op.create_foreign_key('weapon_character_id_fkey', 'weapon', 'character', ['character_id'], ['id'])
    # ### end Alembic commands ###
