"""empty message

Revision ID: b2e45fa075b4
Revises: 6362cb11929a
Create Date: 2025-03-19 14:05:02.344874

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'b2e45fa075b4'
down_revision: Union[str, None] = '6362cb11929a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('weapon', sa.Column('character_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'weapon', 'character', ['character_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'weapon', type_='foreignkey')
    op.drop_column('weapon', 'character_id')
    # ### end Alembic commands ###
